### ISSUE TITLE
gnsstoolbox module missing

### ISSUE THREAD

**Issue by kpant14** [arthurdjn/gnsstools#1]
Can you please add the gnsstoolbox module in the repo?

**Comment by arthurdjn** [comment]
No, the `gnsstoolbox` package is private and was used during a school assigment.
The `gnsstools` should work without `gnsstoolbox` however.

**Comment by kpant14** [comment]
https://github.com/arthurdjn/gnsstools/blob/e496093bcecb4b543d5c73b6f5bdfc70b53dbfab/gnsstools/orbits/orbit.py#L11 
https://github.com/arthurdjn/gnsstools/blob/e496093bcecb4b543d5c73b6f5bdfc70b53dbfab/gnsstools/orbits/orbit.py#L18. 
 The `Orbit()` class inherits some of the functions of gnsstoolbox class. It throws an error when I try to run it. It would be great if you could add those functions to this class if the gnsstoolbox module is proprietary.

**Comment by arthurdjn** [comment]
Yes because the `Orbit` class was only used for the assignment.
This repo was created during a school assignment and is no longer maintained. However, if you find it useful, you can modify the source code and propose a PR ?

If you just wand the package to work, simply remove the orbit import:

https://github.com/arthurdjn/gnsstools/blob/e496093bcecb4b543d5c73b6f5bdfc70b53dbfab/gnsstools/orbits/__init__.py#L8

https://github.com/arthurdjn/gnsstools/blob/e496093bcecb4b543d5c73b6f5bdfc70b53dbfab/gnsstools/__init__.py#L11

Then you can use the package to parse files just like in the readme.
